apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno
  labels:
    app: deno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deno
  template:
    metadata:
      labels:
        app: deno
    spec:
      containers:
      - name: deno
        image: ghcr.io/${IMAGE_NAME}:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
        ports:
        - containerPort: 1993
